# Generated by Django 4.0 on 2021-12-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenditure',
            new_name='ExpenditureModel',
        ),
        migrations.RenameModel(
            old_name='Income',
            new_name='IncomeModel',
        ),
    ]
